Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - db/seeds.rb
    - db/schema.rb
    - db/migrate/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Metrics/AbcSize:
  Exclude:
    - bin/bundle

Metrics/LineLength:
  Exclude:
    - bin/bundle


Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - spec/**/*.rb
    - config/environments/production.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
